import "./globals.css";
import NavbarMain from "./NavbarMain";

export const metadata = {
	title: "topflight-tracker",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<NavbarMain />
				{children}
			</body>
		</html>
	);
}
