import "./globals.css";
import NavbarMain from "./globals/NavbarMain";
import DynamicNavbar from "./globals/DynamicNavbar";
import Footer from "./globals/Footer";

export const metadata = {
	title: "TopflightTracker",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<NavbarMain />
				<DynamicNavbar />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
