import "./globals.css";

import NavbarMain from "./NavbarMain";
import Navbar from "../../components/Navbar";

export const metadata = {
  title: "topflight-tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children, league }) {
  return (
    <html lang="en">
      <body>
        <NavbarMain />
        <Navbar league={league} />

        {/* Page-specific content */}
        <main>{children}</main>

        <footer className="global-footer">
          <p>© 2024 TopFlight Tracker</p>
        </footer>
      </body>
    </html>
  );
}
